In [2]:
import numpy as np

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [5]:
# my_list
my_array

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

In [8]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0],
]
data = np.array(a)

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
type(data)

numpy.ndarray

In [ ]:
## ndarray
- numpy의 핵심인 다차원 행렬 자료구조 클래스

In [16]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)

print(data1)
print(type(data1))
print(arr1)
print(type(arr1))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [19]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [22]:
arr2.shape

(2, 2)

In [24]:
np.zeros((5, 5))
np.empty((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## ndarray 자료형

In [36]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [40]:
arr1 = np.array([1, 2, 3])
print(arr1)
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

[1 2 3]
int64
[1. 2. 3.]
float64


In [41]:
## 산술 연산

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
## indexing & slicing

In [44]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
arr[2:5] = 10
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [52]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [ ]:
## 불리언 값

In [65]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [54]:
names == 'hong'

array([ True, False,  True, False])

In [66]:
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [57]:
data[names == 'hong', 1]

array(['60', '70'], dtype='<U21')

In [58]:
data[names == 'hong', :1]

array([['math'],
       ['eng']], dtype='<U21')

In [59]:
names != 'hong'

array([False,  True, False,  True])

In [60]:
~(names == 'kim')

array([ True, False,  True, False])

In [61]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

In [67]:
## fancy indexing

In [69]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [76]:
arr[[4, 6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [77]:
arr[[-3, -1]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.]])

In [89]:
np.arange(32).reshape(2, 16)
arr = arr.reshape(8, 4) # reshape(행, 열)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [92]:
print(arr[[1, 5]][:, [2, 3]])

[[ 6  7]
 [22 23]]


In [ ]:
## 배열전치

In [93]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [94]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [96]:
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [97]:
## numpy 함수

In [104]:
# samples = np.random.randn(3, 3)
samples = np.random.standard_normal((3, 3))
print(samples)

[[ 0.91994631 -0.127391   -0.98776457]
 [ 0.25439684 -1.03078219 -0.49333233]
 [ 0.90507596  0.45883123  1.25362991]]


In [105]:
arr1 = np.sqrt(samples)
print(arr1)

[[0.95913832        nan        nan]
 [0.50437768        nan        nan]
 [0.9513548  0.67737082 1.11965616]]


C:\Users\1-13\AppData\Local\Temp\ipykernel_13504\1273485535.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [106]:
arr2 = np.abs(samples)
print(arr2)

[[0.91994631 0.127391   0.98776457]
 [0.25439684 1.03078219 0.49333233]
 [0.90507596 0.45883123 1.25362991]]


In [107]:
np.isnan(arr1)

array([[False,  True,  True],
       [False,  True,  True],
       [False, False, False]])